# Generated by Django 6.0.7 on 2026-08-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('nombre_nino', models.CharField(blank=True, max_length=100)),
                ('edad', models.CharField(blank=True, max_length=10)),
                ('asunto', models.CharField(choices=[('programas', 'Consulta sobre programas educativos'), ('visita', 'Solicitar visita al colegio'), ('otro', 'Otro')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
